name: Build and deploy Doxygen documentation

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Doxygen documentation
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: 'Doxyfile'

    - name: Deploy Doxygen Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secret.DOXYGEN}}
        publish_dir: ./public

